services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.[INTERNAL-SUBDOMAIN].duckdns.org"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - ./data:/data
    ports:      # Comment this ports section out after setting up Nginx Reverse Proxy, so that the web GUI can only be accessed through the Proxy
      - 8080:80

# Only add this section after setting up Nginx Reverse Proxy and its docker network
networks:
  default:
    external: true
    name: npm_proxy
