services:
  adguardhome:
    image: 'adguard/adguardhome:latest'
    container_name: 'adguardhome'
    restart: 'unless-stopped'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data:/opt/adguardhome/work' # Data directory
      - './conf:/opt/adguardhome/conf' # Configuration file
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      # DNS over HTTPs
      #- "443:443/tcp"
      # DNS over TLS
      #- "853:853/tcp"
      # DNS over QUIC
      #- "784:784/udp"
      # DNS Crypt
      #- "5443:5443/tcp"
      #- "5443:5443/udp"
      # DHCP Ports
      #- "67:67/udp"
      #- "68:68/tcp"
      #- "68:68/udp"
      # Dashboard
      - 3000:3000/tcp
      - 80:80/tcp
    networks:
      macvlan:
        ipv4_address: 192.168.10.3  # Desired IP address of this DNS Server

networks:
  macvlan:
    driver: macvlan
    enable_ipv6: true    # Optional, only if wanting IPv6 support 
    driver_opts:
      parent: eth0       # Your network interface
    ipam:
      config:
        - subnet: 192.168.10.0/24     # Your home network subnet
          gateway: 192.168.10.254     # Your home network router/gateway for internet access
          ip_range: 192.168.10.3/32   # Desired IP address of this DNS Server

        - subnet: xx:xx:xx:xx::/64     # Your IPv6 subnet here, if needed
          gateway: xx:xx:xx:xx:xx::1   # IPv6 (external) of router
