services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:       # Comment this ports section out after setting up Nginx Reverse Proxy, so that the web GUI can only be accessed through the Proxy
      - "3010:3001"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

# Only add this section after setting up Nginx Proxy Manager and its docker network
networks:
  default:
    external: true
    name: npm_proxy
